#pragma once
#include <SFML/Graphics.hpp>
#include <SFML/System.hpp>
#include <SFML/Window.hpp>
#include <SFML/Audio.hpp>
#include <random>
#include <vector>
#include <memory>
#include <algorithm>
#include <iostream>
#include <filesystem>
#include <fstream>
#include <cstdlib>
#include <future>         
#include <atomic>         
#include <thread>         
#include <chrono>        
#include <regex>
#include <functional>     
#include <ranges>
#include <string>
#include "music.h"
#include "score_storage.h"
#include "ui.h"
